### ISSUE TITLE
Broken Alice-Node

### ISSUE THREAD

**Issue by nicoladiaz** [NInfolab/alice#38]
Recent Version of Alice is not operational : on a fresh installation alice-node does not start  : 

systemctl status alice-node.service && journalctl -xe
● alice-node.service - Alice node service
   Loaded: loaded (/etc/systemd/system/alice-node.service; enabled; vendor prese
t: enabled)
   Active: failed (Result: exit-code) since Sat 2018-03-17 13:50:11 U
TC; 3min 49s ago
  Process: 22667 ExecStart=/usr/bin/node /usr/share/alice/server.js /etc/alice/a
lice.json (code=exited, status=1/FAILURE)
 Main PID: 22667 (code=exited, status=1/FAILURE)

Mar 17 13:50:11 serveur-6 systemd[1]: alice-node.service: Failed with re
sult 'exit-code'.
Mar 17 13:50:11 serveur-6 systemd[1]: alice-node.service: Service hold-off time 
over, scheduling restart.
Mar 17 13:50:11 serveur-6 systemd[1]: Stopped Alice node service.
Mar 17 13:50:11 serveur-6 systemd[1]: alice-node.service: Start request 
repeated too quickly.
Mar 17 13:50:11 serveur-6 systemd[1]: Failed to start Alice node service
.
Mar 17 13:50:11 serveur-6 systemd[1]: alice-node.service: Unit entered f
ailed state.
Mar 17 13:50:11 serveur-6 systemd[1]: alice-node.service: Failed with re
sult 'exit-code'.
Mar 17 13:50:33 serveur-6 systemd[1]: alice-node.service: Start request 
repeated too quickly.
Mar 17 13:50:33 serveur-6 systemd[1]: Failed to start Alice node service
.
Mar 17 13:50:33 serveur-6 systemd[1]: alice-node.service: Failed with re
sult 'exit-code'.

**Comment by angelodlfrtr** [comment]
Done ;)
