### ISSUE TITLE
Problem with SSL Certificates

### ISSUE THREAD

**Issue by maxpearl** [NInfolab/alice#54]
This may be an issue with documentation (or perhaps error handling) more than anything else - I've been trying to get Alice to work and have run into a certificate issue when trying to display the mirror. I've tried installing Alice via the documentation on github pages (http://ninfolab.github.io/alice/) as well as the installation instructions from source. I'm running on Debian 9. Nothing in the log files has been helpful except it's been throwing a 500 error, but no indication of where that's coming from, or what the error is. Suggestions on where to start looking for what might be going wrong?

**Comment by NicolasPetton** [comment]
Max Pearl <notifications@github.com> writes:

> This may be an issue with documentation (or perhaps error handling)
> more than anything else - I've been trying to get Alice to work and
> have run into a certificate issue when trying to display the
> mirror. I've tried installing Alice via the documentation on github
> pages (http://ninfolab.github.io/alice/) as well as the installation
> instructions from source. I'm running on Debian 9. Nothing in the log
> files has been helpful except it's been throwing a 500 error, but no
> indication of where that's coming from, or what the error
> is. Suggestions on where to start looking for what might be going
> wrong?

It might come from Caddy, the latest release has an issue with
Letsencrypt, as it creates a new account for each cert request.  There's
a fix in master, but we have to wait for a release.

**Comment by nicoladiaz** [comment]
hey, you mean a new alice release ?

**Comment by NicolasPetton** [comment]
I mean a new Caddy release (see https://github.com/mholt/caddy/issues/2436).

**Comment by nicoladiaz** [comment]
Everything is fixed . Thx @Caddy Team :)
